name: Run Sync Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script (dry run)
        run: |
          echo "Simulating run of sync.py"
          python sync.py || echo "Script finished with error (expected in dry run)"
